const USER_UPDATE_ONLINE = 'USER_UPDATE_ONLINE';
const ALL_USERS = 'ALL_USERS';

const SET_USER = 'SET_USER';
const INIT_CHAT = 'INIT_CHAT';
const GET_CHATS = 'GET_CHATS';
const NEW_CHAT = 'NEW_CHAT';
const EXISTING_CHAT = 'EXISTING_CHAT';
const CHAT_MESSAGE = 'CHAT_MESSAGE';
const NEW_MESSAGE = 'NEW_MESSAGE';
const CONNECT_TO_CHAT = 'CONNECT_TO_CHAT';
const USER_TYPING = 'USER_TYPING';

module.exports = {
  USER_TYPING,
  USER_UPDATE_ONLINE,
  ALL_USERS,
  SET_USER,
  INIT_CHAT,
  GET_CHATS,
  NEW_CHAT,
  EXISTING_CHAT,
  CHAT_MESSAGE,
  NEW_MESSAGE,
  CONNECT_TO_CHAT,
};
